# Generated by Django 4.1.7 on 2023-04-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstDataList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Product name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(max_length=250, verbose_name='Price')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'First data list',
                'verbose_name_plural': 'First data list',
            },
        ),
        migrations.CreateModel(
            name='SecondDataList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Product name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(max_length=250, verbose_name='Price')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Second data list',
                'verbose_name_plural': 'Second data list',
            },
        ),
        migrations.CreateModel(
            name='ThirdDataList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Product name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(max_length=250, verbose_name='Price')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Third data list',
                'verbose_name_plural': 'Third data list',
            },
        ),
        migrations.RemoveField(
            model_name='secondbook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='thirdbook',
            name='author',
        ),
        migrations.DeleteModel(
            name='FirstBook',
        ),
        migrations.DeleteModel(
            name='SecondBook',
        ),
        migrations.DeleteModel(
            name='ThirdBook',
        ),
    ]
